### POST (Register User)
POST http://localhost:8080/users/
Content-Type: application/json

{
  "username": "fosorio",
  "name": "Francisco Osório",
  "password": "test123"
}

### POST (Register Task)
POST http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic fosorio:test123

{
  "title": "Aplicação spring boot",
  "description": "Desenvolver uma aplicação spring boot",
  "priority": "ALTA",
  "startAt": "2024-07-09T17:00:00",
  "endAt": "2024-07-09T18:00:00"
}

### Get (List Tasks)
GET http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic fosorio:test123

### PUT (Update Task)
PUT http://localhost:8080/tasks/3b2c7d6a-d6ca-44c6-8895-8834201ec4e6
Content-Type: application/json
Authorization: Basic fosorio:test123

{
  "title": "Alteracao Aplicação spring boot"
}
